# Numpy practice session

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
# import numpy library in the jupyter noteboook
import numpy as np

# Creating an array using numpy library

In [3]:
#1_D array
food= np.array(["samosa", "pakora","raita"])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [4]:
price= np.array([5,5,5,])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(price)

3

In [8]:
len(food)

3

In [9]:
price[1]

5

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
food[2]

'raita'

In [12]:
price.mean()

5.0

In [13]:
#zeros method
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [14]:
#ones method
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
#empty
np.empty(6)  #Assignemnt

array([0., 0., 0., 0., 0., 0.])

In [16]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#specify
np.arange(4,40)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39])

In [18]:
#specific interval
np.arange(5,50,10)

array([ 5, 15, 25, 35, 45])

In [19]:
#table of 11
np.arange(11,130,11)

array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121])

In [20]:
#line space
#5 numbers will be displayed with each having an equal distance
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
#specify your data type
np.ones(6,dtype=np.int64)

array([1, 1, 1, 1, 1, 1], dtype=int64)

In [22]:
np.ones(10, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [23]:
a=np.array([2,8,15,36,75,100,0.6,1.6,5.8])
a

array([  2. ,   8. ,  15. ,  36. ,  75. , 100. ,   0.6,   1.6,   5.8])

In [24]:
a.sort()
a

array([  0.6,   1.6,   2. ,   5.8,   8. ,  15. ,  36. ,  75. , 100. ])

In [25]:
b=np.array([10,20.3,4.6,7.8,9.2])
b

array([10. , 20.3,  4.6,  7.8,  9.2])

In [26]:
np.concatenate((a,b))

array([  0.6,   1.6,   2. ,   5.8,   8. ,  15. ,  36. ,  75. , 100. ,
        10. ,  20.3,   4.6,   7.8,   9.2])

In [27]:
c=np.concatenate((a,b))
c

array([  0.6,   1.6,   2. ,   5.8,   8. ,  15. ,  36. ,  75. , 100. ,
        10. ,  20.3,   4.6,   7.8,   9.2])

In [28]:
c.sort()
c

array([  0.6,   1.6,   2. ,   4.6,   5.8,   7.8,   8. ,   9.2,  10. ,
        15. ,  20.3,  36. ,  75. , 100. ])

# 2-Dimensional Array

In [29]:
a=np.array([[1,2,3,4,5,],[5,4,3,2,1,]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [30]:
b=np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [31]:
c= np.concatenate((a,b))
c

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 2

In [ ]:
#Comment for concatenate, To add or subtract matrices, they must be in the same order, and for multiplication, 
#the first matrix’s number of columns must equal the second matrix’s number of rows. 
#Concatenate function can take two or more arrays of the same shape (order).

In [32]:
x=np.array([[2,3],[4,5]])
x

array([[2, 3],
       [4, 5]])

In [33]:
y=np.array([[6,7],[8,9]])
y

array([[6, 7],
       [8, 9]])

In [34]:
z=np.concatenate((x,y), axis=0)
z

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#for different dimensions what to do

In [35]:
z=np.concatenate((x,y), axis=1)
z

array([[2, 3, 6, 7],
       [4, 5, 8, 9]])

In [36]:
#To find the number of dimensions
a.ndim

2

In [37]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
b.ndim

2

In [39]:
#size(number of elements)
b.size

9

In [40]:
#shape (no.of coloumns and rows)
b.shape

(3, 3)

In [41]:
a=np.arange(9) #3*3=9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
#reshape
a=a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
b=np.arange(25) #5*5=25
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
b=b.reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
np.reshape(b, newshape=(1,25), order='C')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a.shape

(9,)

In [48]:
#row wise
b= a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
b.shape

(1, 9)

In [50]:
#coloumn wise
c= a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [51]:
c[3:9]

array([[4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [52]:
a[2,8]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [53]:
c*2

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

In [54]:
c+3

array([[ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [55]:
c.sum()

45

In [56]:
a.mean()

5.0